/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#include <gtest/gtest.h>

#include <EmbeddedProto/ReadBufferFixedSize.h>

namespace test_EmbeddedAMS_ReadBufferFixedSize
{
  TEST(ReadBufferFixedSize, construction) 
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;

    EXPECT_EQ(0, buffer.get_size());
    EXPECT_EQ(BUFFER_SIZE, buffer.get_max_size());

    uint8_t byte = 255;
    EXPECT_FALSE(buffer.peek(byte));
    EXPECT_EQ(255, byte);
    EXPECT_FALSE(buffer.advance());
    EXPECT_FALSE(buffer.advance(1));
    EXPECT_FALSE(buffer.pop(byte));
  }

  TEST(ReadBufferFixedSize, push)
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;

    EXPECT_TRUE(buffer.push(0));
    EXPECT_EQ(1, buffer.get_size());

    EXPECT_TRUE(buffer.push(1));
    EXPECT_EQ(2, buffer.get_size());
    
    EXPECT_TRUE(buffer.push(2));
    EXPECT_EQ(3, buffer.get_size());
    
    EXPECT_FALSE(buffer.push(3));
    EXPECT_EQ(3, buffer.get_size());
  }

  TEST(ReadBufferFixedSize, get_data)
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;

    constexpr std::array<uint8_t, BUFFER_SIZE> data = { 0, 1, 2 };

    memcpy(buffer.get_data(), data.data(), BUFFER_SIZE);
    buffer.set_bytes_written(BUFFER_SIZE);
    EXPECT_EQ(BUFFER_SIZE, buffer.get_size());
  }

  TEST(ReadBufferFixedSize, pop)
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;

    constexpr std::array<uint8_t, BUFFER_SIZE> data = { 0, 1, 2 };

    memcpy(buffer.get_data(), data.data(), BUFFER_SIZE);
    buffer.set_bytes_written(BUFFER_SIZE);
  
    uint8_t byte = 255;
    EXPECT_TRUE(buffer.pop(byte));
    EXPECT_EQ(0, byte);
    EXPECT_TRUE(buffer.pop(byte));
    EXPECT_EQ(1, byte);
    EXPECT_TRUE(buffer.pop(byte));
    EXPECT_EQ(2, byte);
    EXPECT_FALSE(buffer.pop(byte));
    EXPECT_EQ(2, byte); // byte should not have changed.
  }

  TEST(ReadBufferFixedSize, peak)
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;
    constexpr std::array<uint8_t, BUFFER_SIZE> data = { 0, 1, 2 };

    memcpy(buffer.get_data(), data.data(), BUFFER_SIZE);
    buffer.set_bytes_written(BUFFER_SIZE);


    uint8_t byte = 255;
    EXPECT_TRUE(buffer.peek(byte));
    EXPECT_EQ(0, byte);

    // Peaking again should not have moved the read index.
    EXPECT_TRUE(buffer.peek(byte));
    EXPECT_EQ(0, byte);

    buffer.pop(byte);

    EXPECT_TRUE(buffer.peek(byte));
    EXPECT_EQ(1, byte);

    buffer.pop(byte);

    EXPECT_TRUE(buffer.peek(byte));
    EXPECT_EQ(2, byte);

    buffer.pop(byte);
    EXPECT_FALSE(buffer.peek(byte));
  }

  // The batched pop(bytes_view) copies a whole block out and advances the read
  // index by length. It is all-or-nothing: a request larger than the number of
  // bytes available copies nothing and leaves the read index untouched, matching
  // the pop(byte) / advance(n) semantics.
  TEST(ReadBufferFixedSize, pop_block)
  {
    constexpr uint32_t BUFFER_SIZE = 5;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;
    constexpr std::array<uint8_t, BUFFER_SIZE> data = { 10, 11, 12, 13, 14 };

    memcpy(buffer.get_data(), data.data(), BUFFER_SIZE);
    buffer.set_bytes_written(BUFFER_SIZE);

    // Pop the first three bytes in one call.
    std::array<uint8_t, 3> dest = { 0, 0, 0 };
    EXPECT_TRUE(buffer.pop(dest.data(), 3));
    EXPECT_EQ(10, dest[0]);
    EXPECT_EQ(11, dest[1]);
    EXPECT_EQ(12, dest[2]);
    EXPECT_EQ(2, buffer.get_size());

    // Asking for more than remains must fail and consume nothing.
    std::array<uint8_t, 3> dest2 = { 0xFF, 0xFF, 0xFF };
    EXPECT_FALSE(buffer.pop(dest2.data(), 3));
    EXPECT_EQ(0xFF, dest2[0]); // Untouched on a short read.
    EXPECT_EQ(2, buffer.get_size());

    // Exactly emptying the buffer is allowed.
    EXPECT_TRUE(buffer.pop(dest2.data(), 2));
    EXPECT_EQ(13, dest2[0]);
    EXPECT_EQ(14, dest2[1]);
    EXPECT_EQ(0, buffer.get_size());
  }

  TEST(ReadBufferFixedSize, advance)
  {
    constexpr uint32_t BUFFER_SIZE = 3;
    EmbeddedProto::ReadBufferFixedSize<BUFFER_SIZE> buffer;

    EXPECT_TRUE(buffer.push(0));
    EXPECT_TRUE(buffer.advance());
    EXPECT_FALSE(buffer.advance());

    EXPECT_TRUE(buffer.push(1));
    EXPECT_TRUE(buffer.push(2));
    EXPECT_TRUE(buffer.advance());
    EXPECT_TRUE(buffer.advance());

    buffer.clear();
    EXPECT_FALSE(buffer.advance());

    EXPECT_TRUE(buffer.push(0));
    EXPECT_TRUE(buffer.push(1));

    EXPECT_TRUE(buffer.advance(2));
    EXPECT_FALSE(buffer.advance(2));

  }
} // End of namespace test_EmbeddedAMS_ReadBufferFixedSize
