/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#include "gtest/gtest.h"

#include <EmbeddedProto/MessageSizeCalculator.h>

#include <cstdint>
#include <limits> 


namespace test_EmbeddedAMS_MessageSizeCalculator
{

TEST(MessageSizeCalculator, push) 
{
  ::EmbeddedProto::MessageSizeCalculator msc;
  uint8_t byte = 0;
  EXPECT_EQ(0, msc.get_size());
  EXPECT_TRUE(msc.push(byte));
  EXPECT_EQ(1, msc.get_size());
  EXPECT_TRUE(msc.push(byte));
  EXPECT_EQ(2, msc.get_size());

  // Clear the content
  msc.clear();
  EXPECT_EQ(0, msc.get_size());
}

TEST(MessageSizeCalculator, push_n) 
{
  ::EmbeddedProto::MessageSizeCalculator msc;

  static constexpr uint8_t SIZE = 3;
  uint8_t bytes[SIZE] = {1, 2, 3};
  EXPECT_TRUE(msc.push(bytes, SIZE));
  EXPECT_EQ(3, msc.get_size());
}

TEST(MessageSizeCalculator, unlimited_size) 
{
  ::EmbeddedProto::MessageSizeCalculator msc;
  EXPECT_EQ(std::numeric_limits<uint32_t>::max(), msc.get_max_size());
  EXPECT_EQ(std::numeric_limits<uint32_t>::max(), msc.get_available_size());
}

} // End of namespace test_EmbeddedAMS_MessageSizeCalculator