/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

//! End-to-end proof of the dedicated callbackStorage generator option on bytes/string.
/*!
  \brief End-to-end proof of the callbackStorage generator option on bytes/string.

  A singular bytes field (blob) and a singular string field (label) are emitted by the
  generator as BytesStringCallback fields. The generated setters bind the window, the chunk
  callbacks and the length; serialize() writes the LEN prefix from the declared length and
  pulls the payload in windows, deserialize() offers each parsed window to the callback. A
  source -> serialize -> deserialize -> sink round trip therefore runs through the generated
  message with only the windows the test owns resident.
*/

#include "gtest/gtest.h"

#include <EmbeddedProto/ReadBufferFixedSize.h>
#include <EmbeddedProto/WriteBufferFixedSize.h>
#include <EmbeddedProto/BytesStringCallback.h>
#include <EmbeddedProto/MessageState.h>
#include <EmbeddedProto/Errors.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>

#include <callback_storage_bytes.h>

namespace test_EmbeddedAMS_CallbackStorageBytes
{

using ::EmbeddedProto::Error;

using Msg = callback_storage_bytes::CallbackBlobMsg;
using BytesField = ::EmbeddedProto::BytesStringCallback<uint8_t>;
using StringField = ::EmbeddedProto::BytesStringCallback<char>;

//! Window source or sink over a fixed array, tracking its own position; the library passes no offset.
template<class T, std::size_t N>
struct WindowCursor
{
  std::array<T, N> values{};
  uint32_t length = 0U;
  uint32_t position = 0U;

  //! Serialize side: copy the next window out.
  uint32_t produce(::EmbeddedProto::array_view<T> window)
  {
    const uint32_t remaining = length - position;
    const uint32_t n = (remaining < window.size) ? remaining : window.size;
    std::memcpy(window.data, values.data() + position, n);
    position += n;
    return n;
  }

  //! Deserialize side: append the offered window.
  uint32_t consume(::EmbeddedProto::array_view<T> window)
  {
    std::memcpy(values.data() + position, window.data, window.size);
    position += window.size;
    return window.size;
  }
};

using BlobCursor = WindowCursor<uint8_t, 16>;
using LabelCursor = WindowCursor<char, 16>;

//! Copy a write buffer into a read buffer, as a transport would.
template<class WriteBuffer, class ReadBuffer>
static void transfer(WriteBuffer& from, ReadBuffer& to)
{
  for(uint32_t i = 0U; i < from.get_size(); ++i)
  {
    to.push(from.get_data()[i]);
  }
}

//! Both fields of a message bound to their windows and, per direction, their cursors.
struct Bound
{
  std::array<uint8_t, 4> blob_window{};
  std::array<char, 8> label_window{};
  BlobCursor blob;
  LabelCursor label;
  BytesField::ChunkCallback blob_cb;
  StringField::ChunkCallback label_cb;

  void as_source(Msg& msg)
  {
    blob_cb.set<BlobCursor, &BlobCursor::produce>(&blob);
    label_cb.set<LabelCursor, &LabelCursor::produce>(&label);
    msg.set_blob_window({blob_window.data(), 4U});
    msg.set_label_window({label_window.data(), 8U});
    msg.set_blob_on_serialize_chunk(blob_cb);
    msg.set_label_on_serialize_chunk(label_cb);
    msg.set_blob_length(blob.length);
    msg.set_label_length(label.length);
  }

  void as_sink(Msg& msg)
  {
    blob_cb.set<BlobCursor, &BlobCursor::consume>(&blob);
    label_cb.set<LabelCursor, &LabelCursor::consume>(&label);
    msg.set_blob_window({blob_window.data(), 4U});
    msg.set_label_window({label_window.data(), 8U});
    msg.set_blob_on_deserialize_chunk(blob_cb);
    msg.set_label_on_deserialize_chunk(label_cb);
  }
};

// The generated setters bind both directions; serialized_size() reports the declared lengths
// without pulling, and the round trip streams the blob through a window smaller than the value.
TEST(CallbackStorageBytes, round_trip_source_to_sink)
{
  Bound out_side;
  out_side.blob.values = {1U, 2U, 3U, 4U, 5U, 6U, 7U, 8U, 9U, 10U};
  out_side.blob.length = 10U;
  const char text[] = "streaming";
  std::memcpy(out_side.label.values.data(), text, 9U);
  out_side.label.length = 9U;

  Msg out;
  out_side.as_source(out);

  // [tag][10][payload] + [tag][9][payload], nothing pulled for the size.
  EXPECT_EQ(23U, out.serialized_size());
  EXPECT_EQ(0U, out_side.blob.position);

  ::EmbeddedProto::WriteBufferFixedSize<64> buffer;
  ASSERT_EQ(Error::NO_ERRORS, out.serialize(buffer));
  EXPECT_EQ(23U, buffer.get_size());

  Bound in_side;
  Msg in;
  in_side.as_sink(in);

  ::EmbeddedProto::ReadBufferFixedSize<64> read_buffer;
  transfer(buffer, read_buffer);
  ASSERT_EQ(Error::NO_ERRORS, in.deserialize(read_buffer));

  ASSERT_EQ(10U, in_side.blob.position);
  EXPECT_EQ(0, std::memcmp(out_side.blob.values.data(), in_side.blob.values.data(), 10U));
  ASSERT_EQ(9U, in_side.label.position);
  EXPECT_EQ(0, std::memcmp(text, in_side.label.values.data(), 9U));
}

// With no length declared both fields are empty, so the message serializes to nothing.
TEST(CallbackStorageBytes, serialize_without_binding_emits_nothing)
{
  Msg out; // nothing bound

  ::EmbeddedProto::WriteBufferFixedSize<64> buffer;
  ASSERT_EQ(Error::NO_ERRORS, out.serialize(buffer));
  EXPECT_EQ(0U, buffer.get_size());
}

#ifdef PARTIAL_SERIALIZATION_ENABLED

// Partial serialize-out: a small write buffer forces the payload to split, every window is
// pulled once, and the bytes round-trip back through a sink-backed message.
TEST(CallbackStorageBytes, partial_serialize_out_across_split_round_trips)
{
  Bound out_side;
  out_side.blob.values = {1U, 2U, 3U, 4U, 5U};
  out_side.blob.length = 5U;

  Msg out;
  out_side.as_source(out);
  Msg::StateStack out_state;

  ::EmbeddedProto::WriteBufferFixedSize<3> chunk;
  ::EmbeddedProto::ReadBufferFixedSize<64> wire;
  Error result = Error::BUFFER_FULL;
  uint32_t guard = 0U;
  while((Error::BUFFER_FULL == result) && (guard < 100U))
  {
    result = out.serialize_partial(chunk, out_state.root());
    ASSERT_TRUE((Error::NO_ERRORS == result) || (Error::BUFFER_FULL == result));
    transfer(chunk, wire);
    chunk.clear();
    ++guard;
  }
  ASSERT_EQ(Error::NO_ERRORS, result);

  Bound in_side;
  Msg in;
  in_side.as_sink(in);
  ASSERT_EQ(Error::NO_ERRORS, in.deserialize(wire));

  ASSERT_EQ(5U, in_side.blob.position);
  EXPECT_EQ(0, std::memcmp(out_side.blob.values.data(), in_side.blob.values.data(), 5U));
  EXPECT_EQ(0U, in_side.label.position);
}

#endif // PARTIAL_SERIALIZATION_ENABLED

} // namespace test_EmbeddedAMS_CallbackStorageBytes
