/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

/*!
  \brief Unit tests for BytesStringCallback.

  A callback storage string/bytes field streams in windows. The window is the interface seam: serialize pulls windows from the user until the
  declared length is written, deserialize offers each parsed window to the user. The
  tests check the framing against a resident FieldBytes, the window sizes offered and
  the two stop conditions (a short serialize source, a short deserialize accept).
*/

#include "gtest/gtest.h"

#include <EmbeddedProto/ReadBufferFixedSize.h>
#include <EmbeddedProto/WriteBufferFixedSize.h>
#include <EmbeddedProto/BytesStringCallback.h>
#include <EmbeddedProto/FieldStringBytes.h>
#include <EmbeddedProto/MessageState.h>
#include <EmbeddedProto/Errors.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <initializer_list>

namespace test_EmbeddedAMS_BytesStringCallback
{

using ::EmbeddedProto::Error;
using ::EmbeddedProto::MessageState;
using ::EmbeddedProto::FieldProcessingPhase;

using Chunked = ::EmbeddedProto::BytesStringCallback<uint8_t>;

//! The window bound to a field in these tests holds three bytes, so a payload of five needs two windows.
static constexpr uint32_t WINDOW = 3U;

//! Serialize source: copies a fixed payload out in windows and records every window size offered.
template<std::size_t N>
struct WindowSource
{
  std::array<uint8_t, N> values{};
  uint32_t size = 0U;       //!< Bytes the source really has, may be less than declared.
  uint32_t sent = 0U;
  std::array<uint32_t, 8> offered{};
  uint32_t calls = 0U;

  uint32_t operator()(::EmbeddedProto::bytes_view window)
  {
    offered[calls] = window.size;
    ++calls;
    const uint32_t remaining = size - sent;
    const uint32_t n = (remaining < window.size) ? remaining : window.size;
    std::memcpy(window.data, values.data() + sent, n);
    sent += n;
    return n;
  }
};

//! Deserialize sink: appends each window to a fixed buffer, accepting at most accept_limit bytes per window.
template<std::size_t N>
struct WindowSink
{
  std::array<uint8_t, N> values{};
  uint32_t count = 0U;
  uint32_t accept_limit = UINT32_MAX;
  std::array<uint32_t, 8> offered{};
  uint32_t calls = 0U;

  uint32_t operator()(::EmbeddedProto::bytes_view window)
  {
    offered[calls] = window.size;
    ++calls;
    const uint32_t n = (accept_limit < window.size) ? accept_limit : window.size;
    std::memcpy(values.data() + count, window.data, n);
    count += n;
    return n;
  }
};

//! Assert a sink received exactly the expected bytes, in order.
template<std::size_t N>
static void expect_received(const WindowSink<N>& sink, std::initializer_list<uint8_t> expected)
{
  ASSERT_EQ(expected.size(), sink.count);
  std::size_t i = 0U;
  for(uint8_t value : expected)
  {
    EXPECT_EQ(value, sink.values[i]);
    ++i;
  }
}

//! Copy the contents of a write buffer into a read buffer, as a transport would.
template<class ReadBuffer, class WriteBuffer>
static void transfer(WriteBuffer& from, ReadBuffer& to)
{
  for(uint32_t i = 0U; i < from.get_size(); ++i)
  {
    to.push(from.get_data()[i]);
  }
}

// --- Binding / default state -----------------------------------------------

TEST(BytesStringCallback, default_state)
{
  Chunked unbound;
  EXPECT_FALSE(unbound.is_on_serialize_chunk_set());
  EXPECT_FALSE(unbound.is_on_deserialize_chunk_set());
  EXPECT_FALSE(unbound.is_strict());
  EXPECT_EQ(0U, unbound.get_length());
  EXPECT_FALSE(unbound.is_window_set());
  EXPECT_EQ(0U, unbound.get_window_size());
  EXPECT_EQ(UINT32_MAX, unbound.get_max_length());
}

TEST(BytesStringCallback, set_copies_bindings_and_length_clear_forgets_length)
{
  WindowSource<1> source;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);
  field.set_length(7U);
  field.set_strict(true);

  Chunked copy;
  EXPECT_EQ(Error::NO_ERRORS, copy.set(field));
  EXPECT_TRUE(copy.is_on_serialize_chunk_set());
  EXPECT_EQ(WINDOW, copy.get_window_size());
  EXPECT_EQ(7U, copy.get_length());
  EXPECT_TRUE(copy.is_strict());

  copy.clear();
  EXPECT_EQ(0U, copy.get_length());
  EXPECT_TRUE(copy.is_on_serialize_chunk_set());
}

// --- Serialize ---------------------------------------------------------------

// The declared length frames the field exactly like a resident FieldBytes, and the payload is
// pulled in windows of at most WINDOW_SIZE without pulling anything for serialized_size().
TEST(BytesStringCallback, serialize_frames_like_resident_field_in_windows)
{
  const uint32_t field_number = 3U;

  ::EmbeddedProto::FieldBytes<8> resident;
  const uint8_t data[] = {1U, 2U, 3U, 4U, 5U};
  (void)resident.set(data, 5U);
  ::EmbeddedProto::WriteBufferFixedSize<16> expected;
  ASSERT_EQ(Error::NO_ERRORS, resident.serialize_len(field_number, resident.get_length(), expected, true));

  WindowSource<5> source;
  source.values = {1U, 2U, 3U, 4U, 5U};
  source.size = 5U;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);
  field.set_length(5U);

  ::EmbeddedProto::WriteBufferFixedSize<16> buffer;
  ASSERT_EQ(Error::NO_ERRORS, field.serialize_len(field_number, field.get_length(), buffer, true));

  ASSERT_EQ(expected.get_size(), buffer.get_size());
  EXPECT_EQ(0, std::memcmp(expected.get_data(), buffer.get_data(), buffer.get_size()));

  // Two windows: a full one of three and the remaining two.
  ASSERT_EQ(2U, source.calls);
  EXPECT_EQ(3U, source.offered[0]);
  EXPECT_EQ(2U, source.offered[1]);
}

// A source that runs dry before the declared length can not honour the prefix.
TEST(BytesStringCallback, serialize_source_shorter_than_length_is_mismatch)
{
  WindowSource<5> source;
  source.size = 2U;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);
  field.set_length(5U);

  ::EmbeddedProto::WriteBufferFixedSize<16> buffer;
  EXPECT_EQ(Error::CALLBACK_SIZE_MISMATCH, field.serialize(buffer));
}

TEST(BytesStringCallback, serialize_length_without_callback_errors)
{
  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_length(5U);
  ::EmbeddedProto::WriteBufferFixedSize<16> buffer;
  EXPECT_EQ(Error::CALLBACK_NOT_SET, field.serialize(buffer));
}

// A callback without memory to stage a window in can not run.
TEST(BytesStringCallback, streaming_without_window_errors)
{
  WindowSource<1> source;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);
  WindowSink<8> sink;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  Chunked field;
  field.set_on_serialize_chunk(source_cb);
  field.set_on_deserialize_chunk(sink_cb);
  field.set_length(5U);

  ::EmbeddedProto::WriteBufferFixedSize<16> write_buffer;
  EXPECT_EQ(Error::CALLBACK_NOT_SET, field.serialize(write_buffer));
  ::EmbeddedProto::ReadBufferFixedSize<16> read_buffer({0x05U, 1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(Error::CALLBACK_NOT_SET, field.deserialize(read_buffer));
  EXPECT_EQ(0U, sink.calls);
}

TEST(BytesStringCallback, serialize_zero_length_pulls_nothing)
{
  WindowSource<1> source;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);

  ::EmbeddedProto::WriteBufferFixedSize<16> buffer;
  EXPECT_EQ(Error::NO_ERRORS, field.serialize_len(1U, field.get_length(), buffer, false));
  EXPECT_EQ(0U, buffer.get_size());
  EXPECT_EQ(0U, source.calls);
}

// A window is never larger than the room left, so a produced window always fits.
TEST(BytesStringCallback, serialize_window_limited_by_buffer_room)
{
  WindowSource<5> source;
  source.values = {1U, 2U, 3U, 4U, 5U};
  source.size = 5U;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);
  field.set_length(5U);

  ::EmbeddedProto::WriteBufferFixedSize<4> buffer;
  EXPECT_EQ(Error::BUFFER_FULL, field.serialize(buffer));
  EXPECT_EQ(4U, buffer.get_size());
  EXPECT_EQ(3U, source.offered[0]);
  EXPECT_EQ(1U, source.offered[1]);
}

// --- Deserialize -------------------------------------------------------------

TEST(BytesStringCallback, deserialize_offers_windows_until_length)
{
  WindowSink<8> sink;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_deserialize_chunk(sink_cb);

  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U, 1U, 2U, 3U, 4U, 5U, 0xFFU});
  EXPECT_EQ(Error::NO_ERRORS, field.deserialize_check_type(buffer, ::EmbeddedProto::WireFormatter::WireType::LENGTH_DELIMITED));
  expect_received(sink, {1U, 2U, 3U, 4U, 5U});
  ASSERT_EQ(2U, sink.calls);
  EXPECT_EQ(3U, sink.offered[0]);
  EXPECT_EQ(2U, sink.offered[1]);
  // The byte behind the value is left for the next field.
  EXPECT_EQ(1U, buffer.get_size());
}

// Accepting less than offered stops the field; only the accepted bytes are consumed.
TEST(BytesStringCallback, deserialize_short_accept_stops)
{
  WindowSink<8> sink;
  sink.accept_limit = 2U;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_deserialize_chunk(sink_cb);

  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U, 1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(Error::CALLBACK_STOPPED, field.deserialize(buffer));
  expect_received(sink, {1U, 2U});
  EXPECT_EQ(3U, buffer.get_size());
}

TEST(BytesStringCallback, deserialize_without_callback_discards)
{
  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U, 1U, 2U, 3U, 4U, 5U, 0xFFU});
  EXPECT_EQ(Error::NO_ERRORS, field.deserialize(buffer));
  EXPECT_EQ(1U, buffer.get_size());
}

TEST(BytesStringCallback, deserialize_strict_without_callback_errors)
{
  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_strict(true);
  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U, 1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(Error::CALLBACK_NOT_SET, field.deserialize(buffer));
}

TEST(BytesStringCallback, deserialize_truncated_value_is_end_of_buffer)
{
  WindowSink<8> sink;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_deserialize_chunk(sink_cb);

  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U, 1U, 2U});
  EXPECT_EQ(Error::END_OF_BUFFER, field.deserialize(buffer));
  expect_received(sink, {1U, 2U});
}

TEST(BytesStringCallback, deserialize_rejects_wrong_wire_type)
{
  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  ::EmbeddedProto::ReadBufferFixedSize<16> buffer({0x05U});
  EXPECT_EQ(Error::INVALID_WIRETYPE, field.deserialize_check_type(buffer, ::EmbeddedProto::WireFormatter::WireType::VARINT));
}

// A string field hands out a string_view and round trips characters.
TEST(BytesStringCallback, string_round_trips_through_string_view)
{
  using ChunkedString = ::EmbeddedProto::BytesStringCallback<char>;
  std::array<char, 4> window{};

  const char text[] = "hello";
  uint32_t sent = 0U;
  auto source = [&](::EmbeddedProto::string_view window) -> uint32_t
  {
    const uint32_t remaining = 5U - sent;
    const uint32_t n = (remaining < window.size) ? remaining : window.size;
    std::memcpy(window.data, text + sent, n);
    sent += n;
    return n;
  };
  ChunkedString::ChunkCallback source_cb;
  source_cb.set(source);

  ChunkedString out;
  out.set_window({window.data(), 4U});
  out.set_on_serialize_chunk(source_cb);
  out.set_length(5U);
  ::EmbeddedProto::WriteBufferFixedSize<16> write_buffer;
  ASSERT_EQ(Error::NO_ERRORS, out.serialize_len(1U, out.get_length(), write_buffer, false));

  std::array<char, 8> received{};
  uint32_t count = 0U;
  auto sink = [&](::EmbeddedProto::string_view window) -> uint32_t
  {
    std::memcpy(received.data() + count, window.data, window.size);
    count += window.size;
    return window.size;
  };
  ChunkedString::ChunkCallback sink_cb;
  sink_cb.set(sink);

  ChunkedString in;
  in.set_window({window.data(), 4U});
  in.set_on_deserialize_chunk(sink_cb);
  ::EmbeddedProto::ReadBufferFixedSize<16> read_buffer;
  transfer(write_buffer, read_buffer);
  uint8_t tag = 0U;
  ASSERT_TRUE(read_buffer.pop(tag));
  ASSERT_EQ(Error::NO_ERRORS, in.deserialize(read_buffer));
  ASSERT_EQ(5U, count);
  EXPECT_EQ(0, std::memcmp(text, received.data(), 5U));
}

#ifdef PARTIAL_SERIALIZATION_ENABLED

// --- Partial -----------------------------------------------------------------

// A small write buffer splits the payload; every byte is pulled exactly once.
TEST(BytesStringCallback, serialize_partial_resumes_without_double_pull)
{
  const uint32_t field_number = 3U;

  ::EmbeddedProto::FieldBytes<8> resident;
  const uint8_t data[] = {1U, 2U, 3U, 4U, 5U};
  (void)resident.set(data, 5U);
  ::EmbeddedProto::WriteBufferFixedSize<16> expected;
  ASSERT_EQ(Error::NO_ERRORS, resident.serialize_len(field_number, resident.get_length(), expected, true));

  WindowSource<5> source;
  source.values = {1U, 2U, 3U, 4U, 5U};
  source.size = 5U;
  Chunked::ChunkCallback source_cb;
  source_cb.set(source);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_serialize_chunk(source_cb);
  field.set_length(5U);

  ::EmbeddedProto::WriteBufferFixedSize<4> buffer;
  MessageState state;

  std::array<uint8_t, 16> accumulated{};
  std::size_t total = 0U;
  uint32_t guard = 0U;
  while((FieldProcessingPhase::COMPLETE != state.phase) && (guard < 100U))
  {
    const Error result = field.serialize_partial_as_field(field_number, buffer, state, true);
    EXPECT_TRUE((Error::NO_ERRORS == result) || (Error::BUFFER_FULL == result));
    std::memcpy(accumulated.data() + total, buffer.get_data(), buffer.get_size());
    total += buffer.get_size();
    buffer.clear();
    ++guard;
  }

  ASSERT_EQ(expected.get_size(), total);
  EXPECT_EQ(0, std::memcmp(expected.get_data(), accumulated.data(), total));
}

// The value straddles a refill: the refill boundary ends a window and bytes_remaining resumes.
TEST(BytesStringCallback, deserialize_partial_streams_across_split)
{
  WindowSink<8> sink;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_deserialize_chunk(sink_cb);

  MessageState state;
  state.phase = FieldProcessingPhase::SIZE;

  ::EmbeddedProto::ReadBufferFixedSize<8> buffer1({0x05U, 0x01U, 0x02U});
  EXPECT_EQ(Error::END_OF_BUFFER, field.deserialize_partial_as_field(buffer1, state));
  expect_received(sink, {1U, 2U});
  EXPECT_EQ(FieldProcessingPhase::DATA, state.phase);
  EXPECT_EQ(3U, state.bytes_remaining);

  ::EmbeddedProto::ReadBufferFixedSize<8> buffer2({0x03U, 0x04U, 0x05U});
  EXPECT_EQ(Error::NO_ERRORS, field.deserialize_partial_as_field(buffer2, state));
  expect_received(sink, {1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(FieldProcessingPhase::COMPLETE, state.phase);
  ASSERT_EQ(2U, sink.calls);
  EXPECT_EQ(2U, sink.offered[0]);
  EXPECT_EQ(3U, sink.offered[1]);
}

// A stopped field keeps a resumable state: after the sink has room again the rest streams.
TEST(BytesStringCallback, deserialize_partial_stop_is_resumable)
{
  WindowSink<8> sink;
  sink.accept_limit = 1U;
  Chunked::ChunkCallback sink_cb;
  sink_cb.set(sink);

  std::array<uint8_t, WINDOW> window{};
  Chunked field;
  field.set_window({window.data(), WINDOW});
  field.set_on_deserialize_chunk(sink_cb);

  MessageState state;
  state.phase = FieldProcessingPhase::SIZE;

  ::EmbeddedProto::ReadBufferFixedSize<8> buffer({0x05U, 1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(Error::CALLBACK_STOPPED, field.deserialize_partial_as_field(buffer, state));
  expect_received(sink, {1U});
  EXPECT_EQ(FieldProcessingPhase::DATA, state.phase);
  EXPECT_EQ(4U, state.bytes_remaining);

  sink.accept_limit = UINT32_MAX;
  EXPECT_EQ(Error::NO_ERRORS, field.deserialize_partial_as_field(buffer, state));
  expect_received(sink, {1U, 2U, 3U, 4U, 5U});
  EXPECT_EQ(FieldProcessingPhase::COMPLETE, state.phase);
}

#endif // PARTIAL_SERIALIZATION_ENABLED

} // namespace test_EmbeddedAMS_BytesStringCallback
