/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include "empty_message.h"

#include <EmbeddedProto/WireFormatter.h>
#include <ReadBufferMock.h>
#include <WriteBufferMock.h>

using ::testing::_;
using ::testing::InSequence;
using ::testing::Return;
using ::testing::SetArgReferee;
using ::testing::DoAll;

namespace test_EmbeddedAMS_empty_messages
{

TEST(EmptyMessages, construction)
{ 
  // Test if using a message with no fields or enums cause build errors. 
  empty_message empty;
}

TEST(EmptyMessage, clear)
{
  empty_message empty;
  empty.clear();
}

TEST(EmptyMessage, serialize)
{
  Mocks::WriteBufferMock buffer;
  empty_message empty;
  EXPECT_EQ(::EmbeddedProto::Error::NO_ERRORS, empty.serialize(buffer));
}

TEST(EmptyMessage, deserialize)
{
  Mocks::ReadBufferMock buffer;
  InSequence s;

  // Some actual data we try to use to deserialize an empty message.
  EXPECT_CALL(buffer, peek(_, _)).Times(1).WillOnce(DoAll(SetArgReferee<1>(0x08), Return(true)));
  EXPECT_CALL(buffer, peek(_, _)).Times(1).WillOnce(DoAll(SetArgReferee<1>(0x01), Return(true)));
  EXPECT_CALL(buffer, peek(_, _)).Times(1).WillOnce(Return(false));
  
  empty_message empty;
  EXPECT_EQ(::EmbeddedProto::Error::NO_ERRORS, empty.deserialize(buffer));
}


} // End of namespace test_EmbeddedAMS_empty_messages
