/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _MOCK_STRING_STORAGE_H_
#define _MOCK_STRING_STORAGE_H_

#include <EmbeddedProto/FieldStringBytes.h>

namespace Mocks
{

//! A user supplied storage type for a string field used to test the customStorage option.
/*!
    It derives from the built in ::EmbeddedProto::FieldString so it provides the complete string
    interface. It exposes a static counter to prove the generated code instantiates this type
    instead of the default storage.
*/
template<uint32_t MAX_LENGTH>
class MockStringStorage final : public ::EmbeddedProto::FieldString<MAX_LENGTH>
{
  public:
    MockStringStorage()
    {
      ++instance_count;
    }

    ~MockStringStorage() override = default;

    //! The number of MockStringStorage objects currently alive. Used by the tests.
    static uint32_t instance_count;
};

template<uint32_t MAX_LENGTH>
uint32_t MockStringStorage<MAX_LENGTH>::instance_count = 0U;

} // namespace Mocks

#endif // _MOCK_STRING_STORAGE_H_
