/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _READ_BUFFER_MOCK_H_
#define _READ_BUFFER_MOCK_H_

#include <gmock/gmock.h>

#include <EmbeddedProto/ReadBufferInterface.h>

namespace Mocks
{

  class ReadBufferMock : public EmbeddedProto::ReadBufferInterface
  {
    public:

      MOCK_CONST_METHOD0(get_size, uint32_t());
      MOCK_CONST_METHOD0(get_max_size, uint32_t());
      
      MOCK_CONST_METHOD1(peek, bool(uint8_t&));
      MOCK_CONST_METHOD2(peek, bool(const uint32_t, uint8_t&));
      
      MOCK_METHOD0(advance, bool());
      MOCK_METHOD1(advance, bool(uint32_t));
      
      MOCK_METHOD1(pop, bool(uint8_t&));
      MOCK_METHOD0(pop, uint8_t());
      MOCK_METHOD1(pop, bool(const EmbeddedProto::bytes_view&));
      MOCK_METHOD2(pop, bool(uint8_t*, const uint32_t));
  };

  //! Matcher for the batched pop(bytes_view) overload, selecting a view of the given size.
  inline ::testing::Matcher<const EmbeddedProto::bytes_view&> ViewOfSize(const uint32_t size)
  {
    return ::testing::Field(&EmbeddedProto::bytes_view::size, size);
  }

} // End of namespace Mocks

#endif // End of _READ_BUFFER_MOCK_H_
