#!/bin/sh

# This file is used to invoke protoc-gen-eams.py as a plugin to protoc on 
# Linux. The reason this has to be used is that protoc expects a binary or
# terminal script as plugin. Directly calling python scripts is not supported.

./venv/bin/python generator/protoc-gen-eams.py --protoc-plugin