/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _EMBEDDED_PROTO_DEFINES_H_
#define _EMBEDDED_PROTO_DEFINES_H_

#include <type_traits>
#include <cstdint>

#if __cplusplus >= 201703L // C++17 and up
#include <memory>
#endif

namespace EmbeddedProto
{

//! Define PARTIAL_SERIALIZATION_ENABLED to enable partial (chunked) serialization
//! and deserialization. When defined the generated messages and the library gain
//! the serialize_partial()/deserialize_partial() methods, which allow (de)serialization
//! to be paused when a buffer is exhausted and resumed with a fresh buffer.
//! When the macro is not defined only the regular, single-call serialize()/deserialize()
//! are available.

#if __cplusplus >= 201703L // C++17 and up
  
  template<class T>
  inline constexpr void destroy_at(T* p) 
  {
    std::destroy_at(p);
  }

#elif __cplusplus >= 201402L // C++14

  template<class T>
  constexpr void destroy_at(T* p) 
  {
    p->~T(); 
  }

#elif __cplusplus >= 201103L // C++11

  template<class T>
  constexpr void destroy_at(T* p) 
  {
    p->~T(); 
  }

#else // Other

  #error "Unsupported version of C++. Embedded Proto supports C++11 and up."

#endif


  //! An simple struct holding both a pointer to an array and the size of that array.
  template<class T>
  struct array_view {
    T* data; //!< A pointer to the start of an array.
    uint32_t size; //!< The number of elements in the array.
  };

  using string_view = array_view<char>;
  using bytes_view = array_view<uint8_t>;

  //! Simple max function as constexpr
  constexpr uint32_t max(const uint32_t a, const uint32_t b)
  {
    return (a > b) ? a : b;    
  }

  //! Simple min function as constexpr
  constexpr uint32_t min(const uint32_t a, const uint32_t b)
  {
    return (a < b) ? a : b;
  }
}

#endif //_EMBEDDED_PROTO_DEFINES_H_