/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _EMPTY_ARRAY_H_
#define _EMPTY_ARRAY_H_

#include <cstdint>

namespace EmbeddedProto
{
  namespace internal
  {

    //! Stand-in for std::array<T, 0> that is one byte on every standard library.
    /*!
        libc++ gives std::array<T, 0> the size of one T so that data() stays aligned, libstdc++
        makes it one byte. A field with a maximum length of zero holds no element, so the fixed size
        containers use this class instead of the array there. Every element access lands on one
        scratch element shared by all instances for the same T. That keeps an out of range access
        memory safe, but a value written to the scratch element is lost by design.
    */
    template<class T>
    class EmptyArray
    {
      public:
        static constexpr uint32_t size() { return 0U; }

        T* data() { return &storage(); }
        const T* data() const { return &storage(); }

        //! Begin and end are equal, a range based loop does not run.
        T* begin() { return data(); }
        T* end() { return data(); }
        const T* begin() const { return data(); }
        const T* end() const { return data(); }

        //! Any index lands on the scratch element, reset to its default value first.
        T& operator[](uint32_t) { return reset(); }
        const T& operator[](uint32_t) const { return reset(); }

        void fill(const T&) {}

      private:
        static T& storage()
        {
          static T element = T();
          return element;
        }

        static T& reset()
        {
          T& element = storage();
          element = T();
          return element;
        }
    };

  } // End of namespace internal
} // End of namespace EmbeddedProto

#endif // End of _EMPTY_ARRAY_H_
