/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _ERRORS_H_
#define _ERRORS_H_

namespace EmbeddedProto 
{

  //! This enumeration defines errors which can occur during serialization and deserialization. 
  enum class Error
  {
    NO_ERRORS        = 0, //!< No errors have occurred.
    END_OF_BUFFER    = 1, //!< While trying to read from the buffer we ran out of bytes tor read.
    BUFFER_FULL      = 2, //!< The write buffer is full, unable to push more bytes in to it.
    INVALID_WIRETYPE = 3, //!< When reading a Wiretype from the tag we got an invalid value.
    ARRAY_FULL       = 4, //!< The array is full, it is not possible to push more items in it.
    INVALID_FIELD_ID = 5, //!< When the id obtained from the tag equeals zero.
    OVERLONG_VARINT  = 6, //!< The maximum number of bytes where read for this varint but we did not reach the end of the data.
    INDEX_OUT_OF_BOUND = 7, //!< You are trying to access an index outside of valid data.
    // Errors for partial serialization/deserialization
    STATE_MISMATCH   = 10, //!< The state object does not match the message type.
    NESTING_TOO_DEEP = 11, //!< Message nesting exceeds the state stack depth.
    // Errors for callback (streaming) field storage
    CALLBACK_NOT_SET = 12, //!< A callback field was serialized/deserialized without a bound source/sink.
    CALLBACK_SEQUENCE = 13, //!< Callback field requires single-pass access; a size pass or packed encoding attempted on a streaming field violates this constraint.
    CALLBACK_SIZE_MISMATCH = 14, //!< The size reported by the user callback does not match the bytes streamed.
    CALLBACK_STOPPED = 15, //!< A chunk callback accepted fewer bytes than offered, stopping the field before its end.
  };

}; // End of namespace EmbeddedProto

#endif // End of _ERRORS_H_