/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _EMBEDDED_PROTO_VERSION_H_
#define _EMBEDDED_PROTO_VERSION_H_

//! The major version number of the Embedded Proto library.
#define EMBEDDEDPROTO_VERSION_MAJOR 4

//! The minor version number of the Embedded Proto library.
#define EMBEDDEDPROTO_VERSION_MINOR 0

//! The patch version number of the Embedded Proto library.
#define EMBEDDEDPROTO_VERSION_PATCH 0

//! The complete version string of the Embedded Proto library.
#define EMBEDDEDPROTO_VERSION_STRING "4.0.0"

#endif // _EMBEDDED_PROTO_VERSION_H_
