/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _WRITE_BUFFER_FIXED_H_
#define _WRITE_BUFFER_FIXED_H_

#include "WriteBufferInterface.h"
#include <array>

namespace EmbeddedProto 
{

  template<uint32_t BUFFER_SIZE>
  class WriteBufferFixedSize : public ::EmbeddedProto::WriteBufferInterface
  {  
    public:
      WriteBufferFixedSize() = default;
      ~WriteBufferFixedSize() override = default;
  
      //! \see ::EmbeddedProto::WriteBufferInterface::clear()
      void clear() override
      {
        write_index_ = 0;
      }
  
  
      //! \see ::EmbeddedProto::WriteBufferInterface::get_size()
      uint32_t get_size() const override
      {
         return write_index_;
      }
  
  
      //! \see ::EmbeddedProto::WriteBufferInterface::get_max_size()
      uint32_t get_max_size() const override
      {
        return BUFFER_SIZE;
      }
  
      //! \see ::EmbeddedProto::WriteBufferInterface::get_available_size()
      uint32_t get_available_size() const override
      {
        return BUFFER_SIZE - write_index_;
      }
  
      //! \see ::EmbeddedProto::WriteBufferInterface::push()
      bool push(const uint8_t byte) override
      {
        bool return_value = BUFFER_SIZE > write_index_;
        if(return_value)
        {
          data_[write_index_] = byte;
          ++write_index_;
        }
        return return_value;
      }
  
      //! \see ::EmbeddedProto::WriteBufferInterface::push()
      bool push(const uint8_t* bytes, const uint32_t length) override
      {
        // Use >= so a block that exactly fills the remaining space still fits,
        // matching the single-byte push() which allows filling up to BUFFER_SIZE.
        bool return_value = BUFFER_SIZE >= (write_index_ + length);
        if(return_value)
        {
          memcpy(data_.data() + write_index_, bytes, length);
          write_index_ += length;
        }
        return return_value;
      }
  
      //! Return a pointer to the data array.
      uint8_t* get_data()
      {
        return data_.data();
      }
  
    private:
  
      //! The array in which the serialized data is stored.
      std::array<uint8_t, BUFFER_SIZE> data_ = {0};
  
      //! The number of bytes currently serialized in the array.
      uint32_t write_index_ = 0 ;
  
  };

} // End of namespace EmbeddedProto


#endif // _WRITE_BUFFER_FIXED_H_ 
