/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

/*! \mainpage Source code documentation
 *
 * <p>These pages provide you with information with regard to the source code. It is mend for 
 * programmers looking deeper into the workings of %EmbeddedProto.</p>
 *
 * <p>General information on how to use %EmbeddedProto can be found on the main website of 
 * %EmbeddedProto in on the <a href="https://embeddedproto.com/documentation/">Documentation</a> 
 * page. If your are looking for examples you can visit the 
 * <a href="https://embeddedproto.com/examples/">examples</a> page.</p> 
 *
 * <p>Embedded Proto is dual licensed. You may use it under the terms of the
 * GNU General Public License version 3 (GPLv3) as published by the Free
 * Software Foundation, or under a commercial license from Embedded AMS B.V.</p>
 *
 * <p>Under the GPLv3 you must release the source code of any product that
 * includes Embedded Proto or code generated by it. A commercial license
 * removes that obligation. See <a href="https://embeddedproto.com/pricing/">embeddedproto.com/pricing</a>.</p>
 *
 * <p>Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the LICENSE file in the root of the repository for details.</p>
 *
 * <p>
 * Embedded AMS B.V.<br>
 * Atoomweg 2, 1627 LE Hoorn, the Netherlands<br>
 * info at %EmbeddedProto dot com</p>
 *
 */