/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is open source software: you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation, version 3 of the license.
 *
 *  Embedded Proto  is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Embedded Proto. If not, see <https://www.gnu.org/licenses/>.
 *
 *  For commercial and closed source application please visit:
 *  <https://embeddedproto.com/pricing/>.
 *
 *  Embedded AMS B.V.
 *  Info:
 *    info at EmbeddedProto dot com
 *
 *  Postal address:
 *    Atoomweg 2
 *    1627 LE, Hoorn
 *    the Netherlands
 */

// Proves RepeatedFieldCallback plugs into a real generated message through the existing
// customStorage option, with no generator change. The repeated scalar field can be
// instantiated with either a resident storage type or RepeatedFieldCallback.

syntax = "proto3";

import "embedded_proto_options.proto";

package callback_storage;

enum Status
{
  STATUS_OFF = 0;
  STATUS_ON = 1;
  STATUS_ERROR = 2;
}

message CallbackStorageMsg
{
  repeated int32 values = 1 [(EmbeddedProto.options).customStorage = true];
  repeated Status statuses = 2 [(EmbeddedProto.options).customStorage = true];
}
