#
# Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
#
# This file is part of Embedded Proto.
#
# Embedded Proto is dual licensed. You may use it under the terms of the
# GNU General Public License version 3 (GPLv3) as published by the Free
# Software Foundation, or under a commercial license from Embedded AMS B.V.
#
# Under the GPLv3 you must release the source code of any product that
# includes Embedded Proto or code generated by it. A commercial license
# removes that obligation. See <https://embeddedproto.com/pricing/>.
#
# Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the LICENSE file in the root of the repository for details.
#
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
#
# Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
#


"""Unit tests for the version parsing in EmbeddedProto/main.py."""

import os
import sys
import unittest

# Make the repository root importable when run as `python -m unittest`.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from EmbeddedProto.main import parse_version, load_version_info


class TestParseVersion(unittest.TestCase):

    def test_final_release(self):
        self.assertEqual(parse_version("4.1.0"),
                         {"major": 4, "minor": 1, "patch": 0, "string": "4.1.0"})

    def test_beta_release(self):
        self.assertEqual(parse_version("4.1.0b1"),
                         {"major": 4, "minor": 1, "patch": 0, "string": "4.1.0b1"})

    def test_release_candidate(self):
        self.assertEqual(parse_version("4.1.0rc2"),
                         {"major": 4, "minor": 1, "patch": 0, "string": "4.1.0rc2"})

    def test_development_build(self):
        self.assertEqual(parse_version("4.0.12.dev7"),
                         {"major": 4, "minor": 0, "patch": 12, "string": "4.0.12.dev7"})

    def test_malformed(self):
        for bad in ["4.1", "v4.1.0", "4.1.x", ""]:
            with self.subTest(version=bad):
                with self.assertRaises(Exception):
                    parse_version(bad)

    def test_load_version_info_reads_version_json(self):
        info = load_version_info()
        for key in ("major", "minor", "patch"):
            self.assertIsInstance(info[key], int)
        self.assertTrue(info["string"].startswith("%d.%d.%d" % (info["major"], info["minor"], info["patch"])))


if __name__ == "__main__":
    unittest.main()
