#!/usr/bin/env bash
#
# Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
#
# This file is part of Embedded Proto.
#
# Embedded Proto is dual licensed. You may use it under the terms of the
# GNU General Public License version 3 (GPLv3) as published by the Free
# Software Foundation, or under a commercial license from Embedded AMS B.V.
#
# Under the GPLv3 you must release the source code of any product that
# includes Embedded Proto or code generated by it. A commercial license
# removes that obligation. See <https://embeddedproto.com/pricing/>.
#
# Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the LICENSE file in the root of the repository for details.
#
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
#
# Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
#

# Fail on first non-zero return code
set -exuo pipefail

# Run from the repo root regardless of the directory the script is called from.
cd "$(dirname "$0")/.."

# Convert user-friendly parameter to the compiler define enabling partial mode.
# The serialization mode and, optionally, the extra build defines to test with.
EP_DEFINES=""
MODE_NAME="full"
EXTRA_DEFINES=""

usage() {
  echo "Usage: $0 [MODE] [nullterm]"
  echo "  MODE: 'full' (default) or 'partial'"
  echo "        Full mode: Traditional serialization (complete in one call)"
  echo "        Partial mode: Chunked serialization for constrained environments"
  echo "  nullterm: also define NULL_TERMINATED_STRINGS, reserving a null terminator per string"
  echo ""
  echo "Examples:"
  echo "  $0                    # Build with full serialization (default)"
  echo "  $0 full               # Build with full serialization"
  echo "  $0 partial            # Build with partial serialization"
  echo "  $0 partial nullterm   # Partial serialization with null terminated strings"
}

for ARG in "$@"; do
  case "${ARG}" in
    full)
      EP_DEFINES=""
      MODE_NAME="full"
      ;;
    partial)
      EP_DEFINES="-DPARTIAL_SERIALIZATION_ENABLED"
      MODE_NAME="partial"
      ;;
    nullterm)
      EXTRA_DEFINES="-DNULL_TERMINATED_STRINGS"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
EP_DEFINES="${EP_DEFINES} ${EXTRA_DEFINES}"

echo "Building tests with ${MODE_NAME} serialization mode..."

# Build the tests
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${EP_DEFINES}" -B./build/test
make -j16 -C ./build/test
