#!/usr/bin/env bash
#
# Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
#
# This file is part of Embedded Proto.
#
# Embedded Proto is dual licensed. You may use it under the terms of the
# GNU General Public License version 3 (GPLv3) as published by the Free
# Software Foundation, or under a commercial license from Embedded AMS B.V.
#
# Under the GPLv3 you must release the source code of any product that
# includes Embedded Proto or code generated by it. A commercial license
# removes that obligation. See <https://embeddedproto.com/pricing/>.
#
# Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the LICENSE file in the root of the repository for details.
#
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
#
# Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
#
set -euxo pipefail

# Run from the repo root regardless of the directory the script is called from.
cd "$(dirname "$0")/.."

./build/test/test_EmbeddedProto --gtest_output="xml:build/test/test_details.xml"

rm -rf ./code_coverage_report/*
mkdir -p code_coverage_report

if [ $# -eq 0 ]; then
  # No arguments provided, execte the analyisis for sonar qube.
  gcovr --exclude external/ --exclude test/ --sonarqube -o code_coverage_report/coverage.xml

else
# Pass commands
case "$1" in
  -l|--local)
    # Run the code coverage for local machine analysis
    gcovr --exclude external/ --exclude test/ --html --html-details -o code_coverage_report/index.html
    ;;
  *)
    ;;
esac
fi
