/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of any product that
 *  includes Embedded Proto or code generated by it. A commercial license
 *  removes that obligation. See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _EMBEDDED_PROTO_H_
#define _EMBEDDED_PROTO_H_

//! Includes the whole Embedded Proto library.
/*!
    One include for users who do not want to pick headers. Every header of the library is also
    available on its own as <EmbeddedProto/Name.h>, which keeps compile times down when only a
    few are needed.
*/
#include <EmbeddedProto/BytesStringCallback.h>
#include <EmbeddedProto/Defines.h>
#include <EmbeddedProto/EmptyArray.h>
#include <EmbeddedProto/Errors.h>
#include <EmbeddedProto/Fields.h>
#include <EmbeddedProto/FieldStringBytes.h>
#include <EmbeddedProto/Functional.h>
#include <EmbeddedProto/MessageCallback.h>
#include <EmbeddedProto/MessageInterface.h>
#include <EmbeddedProto/MessageSizeCalculator.h>
#include <EmbeddedProto/MessageState.h>
#include <EmbeddedProto/ReadBufferFixedSize.h>
#include <EmbeddedProto/ReadBufferInterface.h>
#include <EmbeddedProto/ReadBufferSection.h>
#include <EmbeddedProto/RepeatedField.h>
#include <EmbeddedProto/RepeatedFieldCallback.h>
#include <EmbeddedProto/RepeatedFieldFixedSize.h>
#include <EmbeddedProto/Version.h>
#include <EmbeddedProto/WireFormatter.h>
#include <EmbeddedProto/WriteBufferFixedSize.h>
#include <EmbeddedProto/WriteBufferInterface.h>

#endif // End of _EMBEDDED_PROTO_H_
